### ISSUE TITLE
affconvert X file extensions

### ISSUE THREAD

**Issue by eribertomota** [simsong/AFFLIBv3#16]
The current version of the affconvert accepts .aff and .raw only. However, the help page shows examples using .iso.

Please, fix this.

Cheers,

Eriberto

**Comment by simsong** [comment]
Yes, you should fix it and submit a pull request. If you wish, I'm happy to make you a maintainer.

**Comment by eribertomota** [comment]
The problem is that the current version doesn't accept .iso files (the
message is 'file not found'). Old versions allow .iso.

Cheers,

Eriberto

2014-10-02 21:02 GMT-03:00 Simson L. Garfinkel notifications@github.com:

**Comment by simsong** [comment]
so fix it!

**Comment by eribertomota** [comment]
I am not a programmer. :-/

I am the new AFFLIB maintainer in Debian.

Thanks for your work over this program.

2014-10-02 21:50 GMT-03:00 Simson L. Garfinkel notifications@github.com:

**Comment by simsong** [comment]
AFFLIB is no longer being maintained.

**Comment by eribertomota** [comment]
Yes, you said. But thanks. :-)

2014-10-02 21:59 GMT-03:00 Simson L. Garfinkel notifications@github.com:

**Comment by sshock** [comment]
FYI, I committed a fix for this to my fork.  Interestingly, it
automatically added it to my existing pull request.  I had no idea it would
do that, but that's neat :)

Phillip Hellewell

**Comment by simsong** [comment]
No, I made you a maintainer. You can just commit to the repository now.

**Comment by sshock** [comment]
On Fri, Oct 3, 2014 at 4:09 AM, Simson L. Garfinkel <
notifications@github.com> wrote:

> No, I made you a maintainer. You can just commit to the repository now.

Can I accept pull requests too?  I couldn't see where to do that.

It seems like it would be easier to just maintain my own fork.

Phillip

**Comment by simsong** [comment]
there is no pending pull request. You must have sent it to another repository.
You are now a maintainer of this repo. You can just push a change to it.
I'm happy for you to maintain your own fork.

**Comment by sshock** [comment]
Ok, thanks.  I will probably just work on my own fork for a while, and then
after a while if I have a handful of fixes, I'll see if I can merge them
into your repo.  It won't be as easy without the ability to merge a pull
request, but it's still doable.

FYI, the reason you don't see a pending pull request is because I closed it
2 days ago after discovering that you didn't want to merge it, and that
even though you made me a maintainer, I didn't see any "Merge Pull Request"
button or anything like that, so I closed it so it wouldn't just sit there
forever.

Phillip

**Comment by simsong** [comment]
You are an authorized contributor to my repository. You can just push to it. You no longer need to do pull requests. You can just push.  You can merge or not. It's completely up to you. 

You NEVER made a pull request into the repository. I never got one. I'm not sure where you sent it, but you didn't send it to simsong/AFFLIBv3.

**Comment by sshock** [comment]
Yes I did make a pull request to your repo; it was 5 days ago.  It is this
one right here:
https://github.com/simsong/AFFLIBv3/pull/17

Phillip

**Comment by simsong** [comment]
Oh. Why did you close it?

**Comment by sshock** [comment]
Because I sent an email saying "I committed a fix for this to my fork.
Interestingly, it automatically added it to my existing pull request." and
then you responded to that with "No, I made you a maintainer.", and I
interpreted that to mean "No, I am not going to merge this for you;
instead, I am making you a maintainer".

Then I discovered that I couldn't merge that pull request, so I closed it
so it wouldn't just sit there.  In addition, I wanted it closed because it
kept showing up with later commits that I made.  I now realize I should
probably only do pull requests from a branch, not my master.

Phillip

**Comment by simsong** [comment]
You were correct. I did not want to manage it. My suspicion is that once you became a maintainer, you were unable to merge the pull request that you had initiated, but I could be wrong.

**Comment by sshock** [comment]
Interesting.  Perhaps there is a rule that says "you can't merge your own
request", hehe.  That or I just couldn't find the "Merge pull request"
button :)

In any case, no worries.  I'll just push directly to it in the future.

Phillip

**Comment by sshock** [comment]
Hi Simson.  I was unable to push to your repo.  I got an error 403.
Here's what it showed exactly:

sshock@sshock:~/tmp/simsong/AFFLIBv3$ git push
Username for 'https://github.com': sshock
Password for 'https://sshock@github.com':
error: The requested URL returned error: 403 while accessing
https://github.com/simsong/AFFLIBv3.git/info/refs
fatal: HTTP request failed

Phillip

**Comment by simsong** [comment]
Sorry, I don't know what to do.

**Comment by Dawuid** [comment]
For the 403 problem maybe you have activated [2FA in GitHub](https://help.github.com/articles/about-two-factor-authentication/). If that is correct you have to use the [app token generated](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) instead of your password

**Comment by simsong** [comment]
I activated it but I don't know about you

---

**Comment by simsong** [comment]
To be clear, 2FA is a per-account thing, not a per-repository thing. However, at this point I really cannot provide you with more support. AFFLIBv3 is an obsolete program and I am no longer maintaining it. You are welcome to do with it what you wish.

**Comment by sshock** [comment]
I'm not sure how this is done with github, but if you'd like to designate
my fork as the current official repository, I'll be happy to take over as
maintainer for the time being.

Phillip

**Comment by simsong** [comment]
How do I do that?

---

**Comment by sshock** [comment]
I see two options:

Option 1. Just modify the README and replace "NOTE: AS OF 2012, AFFLIB IS
NO LONGER BEING MAINTAINED." with "NOTE: AFFLIB is currently maintained at
sshock/AFFLIBv3".

Option 2. Transfer ownership.  There should be a button called "Transfer"
in the repo settings.  This page explains how to do it:
https://help.github.com/articles/transferring-a-repository/

I'm worried option #2 may fail because I already have a fork, but if option
#2 is what you want, and it fails because I have a fork, I'll delete my
fork and we can retry it.  It's not a big deal for me to redo a few commits.

Phillip

**Comment by simsong** [comment]
I picked option #1, as it is easier. 

However, my real goal is to retire AFFLIB. My fear is that as long as it exists, people will be contacting me about it.

**Comment by sshock** [comment]
Thanks.  That works for me.

You can consider option #2 later; depending on how people are finding you,
that may actually help with your goal of not being contacted.

Phillip

**Comment by Dawuid** [comment]
Sorry for not be enough clear. My "guess" answer was for @sshock having activated 2FA in his account :)

**Comment by sshock** [comment]
I never enabled 2FA, and I just checked in my settings and it is off.
